language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
sudo: required
script: phpunit test/Test.php
services:
  - mongodb
  - mysql
  - rethinkdb
notifications:
    on_success: never
    on_failure: never
